name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install python dependencies
        run: pip install PyYAML voluptuous
      - name: Check the ruleset
        run: make check
